### ISSUE TITLE
SERVER: callback error: 'StableDiffusionRequestQueueWorker' object has no attribute 'sdrunner'

### ISSUE THREAD

**Issue by RandomLegend** [w4ffl35/krita_stable_diffusion#34]
**Describe the bug**
When trying to generate an image i get the following error:
`SERVER: callback error: 'StableDiffusionRequestQueueWorker' object has no attribute 'sdrunner'
SERVER WORKER: await connection
SERVER WORKER: waiting for queue`

**To Reproduce**
1. Install according to readme
2. Try to generate an image, doesn't matter if it's txt2img or img2img
3. Nothing happens, a look into the terminal when running krita from it reveals the aforementioned error.

**Screenshots**
![image](https://user-images.githubusercontent.com/38812603/192118035-a3d2059d-add5-45ce-b555-aad8b3551804.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/38812603/192116587-13624194-9cca-490f-8315-cffda3e19462.png)

**Additional context**
Stable Diffusion via a webui works perfectly fine on my system.

**Comment by w4ffl35** [comment]
Thank you for the report. A new release is on its way tonight which should fix this issue.

**Comment by w4ffl35** [comment]
@RandomLegend 

take a look at the latest release

https://github.com/w4ffl35/krita_stable_diffusion/releases/tag/0.2.1

It has an installation script which will set up your `~/stablediffusion` folder for you and tell you where to acquire the model and where to place it.

If you still encounter the reported issue it is likely that you are missing the model or have placed it in the wrong folder. Feel free to join our Discord server (see link in README) and let me know if you continue to have problems with running the plugin

**Comment by RandomLegend** [comment]
Sadly still not resolved.

Used your script, put the model file where it belongs but still get the same exact error and also multiple new ones about several different binaries that lack permission. Even after going through all of them and manually makeing them executable, still doesn't work.

**Comment by RandomLegend** [comment]
Also i just realized, that whenever i launch your stable diffusion, it crashes my cuda utils.

When i do `python -c "import torch; print(torch.cuda.is_available())"` i always get errors back after running your sd. After a reboot i get the expected `True` back.

So i think there is something wrong with that, that's maybe causing the issues here. After i run your sd i cannot run automatic1111's webui anymore until i reboot. Then i can run it all day long, and as soon as i run your's it crashes something with cuda and then i have  to reboot in order to get it working again.

**Comment by w4ffl35** [comment]
@RandomLegend

You may need more than 15 gigs of ram. When the model loads I see my ram usage spike over 20gigs at times (depending on whether or not I have other programs running).

With regard to torch:

you shouldn't need torch installed at all in order to run this plugin. The plugin bundles torch and all other dependencies using pyinstaller, including python.

In the screenshot you posted everything is harmless except for the error at the end `object has no attribute sdrunner` - this error means the model itself failed to load.

Can you post the messages above that one? I'm guessing there's a fatal error further up. 

Also, if you have a few minutes to jump on discord I can try to debug it on a screen share with you.

---

If you understand the technical side of this, here's some more info on what's going on:

Krita runs in its own python instance as well. Krita needs to talk to stablediffusion but can't because of Torch and all the other dependencies, so you either have to install everything to your PC, or find a way to make the Krita python instance talk to the stablediffusion python instance.

Locally on my computer I am able to achieve this in two ways:

1. With this plugin. When using it I don't need to install anything related to python
2. When developing I trigger `pyinstaller.py` using a path to my cuda python binary which has all of the dependencies installed.

**Comment by RandomLegend** [comment]
Yeah i have only a 3070 TI with 8gb of vram.

The whole charm of stable diffusion is that, with specific optimizations, you can run it on regular consumer GPUs. If this plugin can't run on my hardware i don't see any sense in trying to debug it.

Also in my case, i will definetely not get rid of any installed python packages, because i run some other webuis and i need it for that.

So i am sorry, but i guess this is not the right project for me then. Nothing bad, i can still copy images from webui into krita and vice versa.

But thanks anyway!

**Comment by w4ffl35** [comment]
understood @RandomLegend this is a very new project and i'm still working on optimization. keep an eye on it and consider using it when it becomes more consumer friendly.

**Comment by RandomLegend** [comment]
i definetly will!

I wish you the best and hopefully you will emerge with an excellent tool! :-)

**Comment by w4ffl35** [comment]
@RandomLegend if you're still out there, you might want to give this another try. thanks to your bug reports and others i was able to release a significant patch. Version 0.2.2-alpha should fix installation issues. If not, I apologize for poking you again.

**Comment by RandomLegend** [comment]
I am still out there and pokeable :-D 

However i currently have other issues with my system and might just create a new blank user to test your plugin with

**Comment by w4ffl35** [comment]
@RandomLegend make sure you use cuda 11.3 drivers. i'm working on another batch of optimizations as well.

**Comment by awesomebytes** [comment]
I had the same error, rebooted, and then it worked.
